"""
Hand-written gold-standard specs used to ground the Coding Agent.

These are NOT generated by the LLM — you write them once, by hand,
as your "best possible" version of a spec for each domain. At runtime,
the closest matching example (by embedding similarity to the current
spec) is included as a few-shot reference in the Coding Agent's prompt.

Keep these small and clean. Quality over quantity — 8 good examples
beats 20 mediocre ones.
"""

from app.schemas import SpecOutput, EntityDef, FieldDef, EndpointDef, FunctionalRequirement


def _fr(id_: str, desc: str, ac: str) -> FunctionalRequirement:
    return FunctionalRequirement(id=id_, description=desc, acceptance_criteria=ac)


EXAMPLE_BANK: list[SpecOutput] = [
    # --- Inventory Management -------------------------------------------------
    SpecOutput(
        app_name="inventory_app",
        domain="Inventory Management",
        entities=[
            EntityDef(name="Category", table_name="categories", fields=[
                FieldDef(name="name", type="str", unique=True),
            ]),
            EntityDef(name="Product", table_name="products", fields=[
                FieldDef(name="name", type="str"),
                FieldDef(name="sku", type="str", unique=True),
                FieldDef(name="stock_quantity", type="int"),
                FieldDef(name="low_stock_threshold", type="int"),
                FieldDef(name="category_id", type="int"),
            ]),
        ],
        endpoints=[
            EndpointDef(method="POST", path="/products", entity="Product", description="Create a product", fr_ids=["FR-01"]),
            EndpointDef(method="GET", path="/products", entity="Product", description="List all products", fr_ids=["FR-02"]),
            EndpointDef(method="GET", path="/products/{product_id}", entity="Product", description="Get one product", fr_ids=["FR-03"]),
            EndpointDef(method="PUT", path="/products/{product_id}", entity="Product", description="Update a product", fr_ids=["FR-04"]),
            EndpointDef(method="DELETE", path="/products/{product_id}", entity="Product", description="Delete a product", fr_ids=["FR-05"]),
            EndpointDef(method="GET", path="/products/low-stock", entity="Product", description="List products below their low-stock threshold", fr_ids=["FR-06"]),
        ],
        functional_requirements=[
            _fr("FR-01", "User can create a product", "POST /products returns 201 with the created product"),
            _fr("FR-02", "User can list products", "GET /products returns 200 with an array of products"),
            _fr("FR-03", "User can fetch a single product", "GET /products/{id} returns 200 or 404"),
            _fr("FR-04", "User can update a product", "PUT /products/{id} returns 200 with updated fields"),
            _fr("FR-05", "User can delete a product", "DELETE /products/{id} returns 204"),
            _fr("FR-06", "System flags low-stock products", "GET /products/low-stock returns only products where stock_quantity < low_stock_threshold"),
        ],
        validation_rules=["stock_quantity must be >= 0", "sku must be unique"],
    ),

    # --- Expense Tracking -------------------------------------------------------
    SpecOutput(
        app_name="expense_tracker",
        domain="Expense Tracking",
        entities=[
            EntityDef(name="Category", table_name="categories", fields=[
                FieldDef(name="name", type="str", unique=True),
            ]),
            EntityDef(name="Expense", table_name="expenses", fields=[
                FieldDef(name="amount", type="float"),
                FieldDef(name="description", type="str", required=False),
                FieldDef(name="date", type="datetime"),
                FieldDef(name="category_id", type="int"),
            ]),
        ],
        endpoints=[
            EndpointDef(method="POST", path="/expenses", entity="Expense", description="Create an expense", fr_ids=["FR-01"]),
            EndpointDef(method="GET", path="/expenses", entity="Expense", description="List expenses", fr_ids=["FR-02"]),
            EndpointDef(method="GET", path="/expenses/{expense_id}", entity="Expense", description="Get one expense", fr_ids=["FR-03"]),
            EndpointDef(method="PUT", path="/expenses/{expense_id}", entity="Expense", description="Update an expense", fr_ids=["FR-04"]),
            EndpointDef(method="DELETE", path="/expenses/{expense_id}", entity="Expense", description="Delete an expense", fr_ids=["FR-05"]),
            EndpointDef(method="GET", path="/expenses/filter", entity="Expense", description="Filter expenses by category", fr_ids=["FR-06"]),
        ],
        functional_requirements=[
            _fr("FR-01", "User can create an expense", "POST /expenses returns 201"),
            _fr("FR-02", "User can list expenses", "GET /expenses returns 200 with an array"),
            _fr("FR-03", "User can fetch a single expense", "GET /expenses/{id} returns 200 or 404"),
            _fr("FR-04", "User can update an expense", "PUT /expenses/{id} returns 200"),
            _fr("FR-05", "User can delete an expense", "DELETE /expenses/{id} returns 204"),
            _fr("FR-06", "User can filter by category", "GET /expenses/filter?category_id=X returns only matching expenses"),
        ],
        validation_rules=["amount must be greater than zero"],
    ),

    # --- Leave Management ---------------------------------------------------
    SpecOutput(
        app_name="leave_management",
        domain="Leave Management",
        entities=[
            EntityDef(name="Employee", table_name="employees", fields=[
                FieldDef(name="name", type="str"),
                FieldDef(name="email", type="str", unique=True),
            ]),
            EntityDef(name="LeaveRequest", table_name="leave_requests", fields=[
                FieldDef(name="employee_id", type="int"),
                FieldDef(name="start_date", type="datetime"),
                FieldDef(name="end_date", type="datetime"),
                FieldDef(name="status", type="str"),
                FieldDef(name="reason", type="str", required=False),
            ]),
        ],
        endpoints=[
            EndpointDef(method="GET", path="/employees", entity="Employee", description="List employees", fr_ids=["FR-00"]),
            EndpointDef(method="POST", path="/leave-requests", entity="LeaveRequest", description="Submit a leave request", fr_ids=["FR-01"]),
            EndpointDef(method="GET", path="/leave-requests", entity="LeaveRequest", description="List leave requests", fr_ids=["FR-02"]),
            EndpointDef(method="PUT", path="/leave-requests/{id}/approve", entity="LeaveRequest", description="Approve a leave request", fr_ids=["FR-03"]),
            EndpointDef(method="PUT", path="/leave-requests/{id}/reject", entity="LeaveRequest", description="Reject a leave request", fr_ids=["FR-04"]),
        ],
        functional_requirements=[
            _fr("FR-00", "User can list employees", "GET /employees returns 200"),
            _fr("FR-01", "Employee can submit a leave request", "POST /leave-requests returns 201 with status='pending'"),
            _fr("FR-02", "User can list leave requests", "GET /leave-requests returns 200"),
            _fr("FR-03", "Manager can approve a request", "PUT /leave-requests/{id}/approve sets status='approved'"),
            _fr("FR-04", "Manager can reject a request", "PUT /leave-requests/{id}/reject sets status='rejected'"),
        ],
        validation_rules=["end_date must be after start_date"],
    ),

    # --- Student Registration ------------------------------------------------
    SpecOutput(
        app_name="student_registration",
        domain="Student Registration",
        entities=[
            EntityDef(name="Course", table_name="courses", fields=[
                FieldDef(name="title", type="str"),
                FieldDef(name="capacity", type="int"),
            ]),
            EntityDef(name="Student", table_name="students", fields=[
                FieldDef(name="name", type="str"),
                FieldDef(name="email", type="str", unique=True),
            ]),
            EntityDef(name="Enrollment", table_name="enrollments", fields=[
                FieldDef(name="student_id", type="int"),
                FieldDef(name="course_id", type="int"),
            ]),
        ],
        endpoints=[
            EndpointDef(method="GET", path="/courses", entity="Course", description="List courses", fr_ids=["FR-00"]),
            EndpointDef(method="POST", path="/students", entity="Student", description="Register a student", fr_ids=["FR-01"]),
            EndpointDef(method="GET", path="/students", entity="Student", description="List students", fr_ids=["FR-01b"]),
            EndpointDef(method="POST", path="/enrollments", entity="Enrollment", description="Enroll a student in a course", fr_ids=["FR-02"]),
            EndpointDef(method="GET", path="/enrollments", entity="Enrollment", description="List all enrollments", fr_ids=["FR-02b"]),
            EndpointDef(method="GET", path="/courses/{course_id}/students", entity="Enrollment", description="List students in a course", fr_ids=["FR-03"]),
        ],
        functional_requirements=[
            _fr("FR-00", "User can list courses", "GET /courses returns 200"),
            _fr("FR-01", "New student can register", "POST /students returns 201"),
            _fr("FR-01b", "User can list students", "GET /students returns 200"),
            _fr("FR-02", "Student can enroll in a course", "POST /enrollments returns 201, rejected if course is at capacity"),
            _fr("FR-02b", "User can list enrollments", "GET /enrollments returns 200"),
            _fr("FR-03", "User can list students in a course", "GET /courses/{id}/students returns 200"),
        ],
        validation_rules=["enrollment must be rejected if course.capacity is reached"],
    ),

    # --- Library Management ---------------------------------------------------
    SpecOutput(
        app_name="library_management",
        domain="Library Management",
        entities=[
            EntityDef(name="Book", table_name="books", fields=[
                FieldDef(name="title", type="str"),
                FieldDef(name="author", type="str"),
                FieldDef(name="isbn", type="str", unique=True),
                FieldDef(name="available_copies", type="int"),
            ]),
            EntityDef(name="Loan", table_name="loans", fields=[
                FieldDef(name="book_id", type="int"),
                FieldDef(name="borrower_name", type="str"),
                FieldDef(name="due_date", type="datetime"),
                FieldDef(name="returned", type="bool"),
            ]),
        ],
        endpoints=[
            EndpointDef(method="POST", path="/books", entity="Book", description="Add a book", fr_ids=["FR-01"]),
            EndpointDef(method="GET", path="/books", entity="Book", description="List books", fr_ids=["FR-02"]),
            EndpointDef(method="POST", path="/loans", entity="Loan", description="Borrow a book", fr_ids=["FR-03"]),
            EndpointDef(method="GET", path="/loans", entity="Loan", description="List loans", fr_ids=["FR-04b"]),
            EndpointDef(method="PUT", path="/loans/{id}/return", entity="Loan", description="Return a book", fr_ids=["FR-04"]),
        ],
        functional_requirements=[
            _fr("FR-01", "Librarian can add a book", "POST /books returns 201"),
            _fr("FR-02", "User can list books", "GET /books returns 200"),
            _fr("FR-03", "User can borrow a book", "POST /loans decrements available_copies, rejected if 0 available"),
            _fr("FR-04b", "User can list loans", "GET /loans returns 200"),
            _fr("FR-04", "User can return a book", "PUT /loans/{id}/return increments available_copies and sets returned=true"),
        ],
        validation_rules=["cannot borrow a book with 0 available_copies"],
    ),
]


def spec_to_text(spec: SpecOutput) -> str:
    """Flatten a spec into plain text for embedding — this is what gets compared, not the raw JSON."""
    entity_lines = []
    for e in spec.entities:
        field_names = ", ".join(f.name for f in e.fields)
        entity_lines.append(f"{e.name} ({field_names})")
    endpoint_lines = [f"{ep.method} {ep.path}: {ep.description}" for ep in spec.endpoints]
    return (
        f"Domain: {spec.domain}\n"
        f"Entities: {'; '.join(entity_lines)}\n"
        f"Endpoints: {'; '.join(endpoint_lines)}"
    )
